// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZNnVGew94J6Ol9I92RqWBTYxcjjfwaX0',
    appId: '1:1016447262234:web:1b5763e691147a3d463ba3',
    messagingSenderId: '1016447262234',
    projectId: 'valence-d72c4',
    authDomain: 'valence-d72c4.firebaseapp.com',
    storageBucket: 'valence-d72c4.firebasestorage.app',
    measurementId: 'G-DJ26NJBTK7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfEcwnZT4EGnUmjHsYrKhFIGRfteSMlZ8',
    appId: '1:1016447262234:android:8d1934d735d364a4463ba3',
    messagingSenderId: '1016447262234',
    projectId: 'valence-d72c4',
    storageBucket: 'valence-d72c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDixqX7j0kCL8mGfTFCr-MRX8_iB6RtjFg',
    appId: '1:1016447262234:ios:bbdb540e05c2fe45463ba3',
    messagingSenderId: '1016447262234',
    projectId: 'valence-d72c4',
    storageBucket: 'valence-d72c4.firebasestorage.app',
    iosBundleId: 'com.example.valence',
  );
}
